export default  {
    All: [
      {
        id: 1,
        name: "Mannat",
        area: "Pimpri",
        city: "Pune",
        price: 12000,
        rating: 4,
        image: require("../assets/property/1.png"),
      },
      {
        id: 2,
        name: "Mannat1",
        area: "Chinchwad",
        city: "Pune",
        price: 14000,
        rating: 2,
        image: require("../assets/property/1.png"),
      },
      {
        id: 3,
        name: "Mannat3",
        area: "Karve Nagar",
        city: "Pune",
        price: 12000,
        rating: 4,
        image: require("../assets/property/1.png"),
      },
      {
        id: 4,
        name: "Mannat4",
        area: "Bhosari",
        city: "Pune",
        price: 14000,
        rating: 2,
        image: require("../assets/property/1.png"),
      },
    ],
    "Recording Studio": [
      {
        id: 1,
        name: "Mannat",
        area: "Kharadi",
        city: "Pune",
        price: 12000,
        rating: 4,
        image: require("../assets/property/1.png"),
      },
      {
        id: 2,
        name: "Mannat1",
        area: "Dhanori",
        city: "Pune",
        price: 14000,
        rating: 2,
        image: require("../assets/property/1.png"),
      },
    ],
  };